In [7]:
import numpy as np
a = np.array([1,2,3,4,5,6])
a[0]
print(a[:5])


[1 2 3 4 5]


array([1, 2, 3, 4, 5, 6])

In [14]:
import numpy as np
a = np.array([[3,8,0,6],[8,9,0,8]])
b = a[:1]
print(b)
a.ndim

[[3 8 0 6]]


2